# Generated by Django 3.2.9 on 2021-12-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.CharField(max_length=200),
        ),
    ]
