# Generated by Django 3.2.9 on 2021-12-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20211203_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name="Nom de l'image"),
        ),
    ]
