# Generated by Django 3.2.9 on 2021-12-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
