# Generated by Django 3.2.9 on 2021-12-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211202_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescue',
            name='ship',
        ),
        migrations.AddField(
            model_name='rescue',
            name='rescued_ship',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescued_in', to='home.ship'),
        ),
        migrations.AddField(
            model_name='rescue',
            name='save_ship',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savor', to='home.ship'),
        ),
    ]
