# Generated by Django 3.2.9 on 2021-12-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211202_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescue',
            name='lifeguard',
        ),
        migrations.RemoveField(
            model_name='rescue',
            name='rescued',
        ),
        migrations.RemoveField(
            model_name='rescue',
            name='rescued_ship',
        ),
        migrations.RemoveField(
            model_name='rescue',
            name='save_ship',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Rescue',
        ),
        migrations.DeleteModel(
            name='Ship',
        ),
    ]
